apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: mkrish1825/fastapi:latest
          ports:
            - containerPort: 8000
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi
  name: fastapi
spec:
  ports:
    - name: fastapi
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: fastapi
  type: LoadBalancer
